services:
  db:
    image: postgres:16-alpine
    container_name: votacao_postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: votacao_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d votacao_db"]
      interval: 5s
      timeout: 5s
      retries: 5

  db-perf:
    image: postgres:16-alpine
    container_name: votacao_postgres_perf
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: votacao_perf_db
    ports:
      - "5433:5432"
    volumes:
      - postgres_perf_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d votacao_perf_db"]
      interval: 5s
      timeout: 5s
      retries: 5

  api:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: votacao_api
    restart: always
    ports:
      - "8080:8080"
    depends_on:
      db:
        condition: service_healthy
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/votacao_db
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres
      SPRING_FLYWAY_ENABLED: "true"

      

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
      args:
        VITE_API_URL: http://localhost:8080/api/v1
    container_name: votacao_frontend
    restart: always
    ports:
      - "3000:80"
    depends_on:
      - api

  k6:
    image: grafana/k6:latest
    profiles:
      - performance
    volumes:
      - ./backend/performance:/performance:ro
    environment:
      BASE_URL: http://host.docker.internal:8080/api/v1
    extra_hosts:
      - "host.docker.internal:host-gateway"

volumes:
  postgres_data:
  postgres_perf_data: