spring:
  datasource:
    url: jdbc:postgresql://localhost:5433/votacao_perf_db
    username: postgres
    password: postgres
    hikari:
      maximum-pool-size: 50
      minimum-idle: 10
  jpa:
    hibernate:
      ddl-auto: validate
  flyway:
    enabled: true